import './styles/globals.css';
import type { Metadata } from 'next';
import { Bebas_Neue, Josefin_Sans, Inter, Raleway } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

const bebas = Bebas_Neue({
    weight: ['400'],
    variable: '--font-Title',
    fallback: ['Helvetica', 'sans-serif'],
    subsets: ['latin'],
});

const raleway = Raleway({
    weight: ['700'],
    style: ['italic'],
    variable: '--tertiary-Title',
    fallback: ['Helvetica', 'sans-serif'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Alerte Hardware',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            className={`${inter.className} ${bebas.variable} ${raleway.variable}`}
            lang='en'>
            <body className='max-h-screen'>{children}</body>
        </html>
    );
}
